#!/bin/bash
CODEPATH="$PWD"
PYTHONPATH="$CODEPATH/deps/GraphLearn:$PYTHONPATH"
PYTHONPATH="$CODEPATH/deps/EDeN:$PYTHONPATH"
PYTHONPATH="$CODEPATH/deps:$PYTHONPATH"
export  CODEPATH
export  PYTHONPATH
